// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDSSwSv2esB-q8T55BI2kOA-97TkYQRmk',
    appId: '1:237270834595:web:f3cee9b1f263d0a9084e16',
    messagingSenderId: '237270834595',
    projectId: 'wastewise-be353',
    authDomain: 'wastewise-be353.firebaseapp.com',
    databaseURL: 'https://wastewise-be353-default-rtdb.firebaseio.com',
    storageBucket: 'wastewise-be353.firebasestorage.app',
    measurementId: 'G-6PNYB1XXKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5eB4pduJZ0mhZTJJd_OZr-EjMneKTr7E',
    appId: '1:237270834595:android:dba0ffa65c2b63ad084e16',
    messagingSenderId: '237270834595',
    projectId: 'wastewise-be353',
    databaseURL: 'https://wastewise-be353-default-rtdb.firebaseio.com',
    storageBucket: 'wastewise-be353.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLkQKoMIEsYhl-LglE1EllA8t5PLwkx5M',
    appId: '1:237270834595:ios:511a071bec87076b084e16',
    messagingSenderId: '237270834595',
    projectId: 'wastewise-be353',
    databaseURL: 'https://wastewise-be353-default-rtdb.firebaseio.com',
    storageBucket: 'wastewise-be353.firebasestorage.app',
    iosBundleId: 'com.example.wasteWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLkQKoMIEsYhl-LglE1EllA8t5PLwkx5M',
    appId: '1:237270834595:ios:511a071bec87076b084e16',
    messagingSenderId: '237270834595',
    projectId: 'wastewise-be353',
    databaseURL: 'https://wastewise-be353-default-rtdb.firebaseio.com',
    storageBucket: 'wastewise-be353.firebasestorage.app',
    iosBundleId: 'com.example.wasteWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDSSwSv2esB-q8T55BI2kOA-97TkYQRmk',
    appId: '1:237270834595:web:fefa546d40164003084e16',
    messagingSenderId: '237270834595',
    projectId: 'wastewise-be353',
    authDomain: 'wastewise-be353.firebaseapp.com',
    databaseURL: 'https://wastewise-be353-default-rtdb.firebaseio.com',
    storageBucket: 'wastewise-be353.firebasestorage.app',
    measurementId: 'G-ZT3Z6YSDWM',
  );
}
